---
environment_vars:
  LANG: C
  LC_ALL: C
  LC_MESSAGES: C
  # https://github.com/ansible/ansible-modules-core/issues/3706
  LS_COLORS: ''

git_repositories:
  - repo: "https://bitbucket.org/nakahiro386/dotfiles.git"
    name: "dotfiles"
  - repo: "https://github.com/nakahiro386/vimfiles.git"
    name: "vimfiles"

bash_profile_path: "~/.profile"
nakahiro386_apt_present_packages:
  - 'software-properties-common'
  - 'python3-apt'
  - 'aptitude'
  - 'language-pack-ja'
  - 'bash-completion'
  - 'git'
  - 'vim'
  # - 'vim-gtk3'
  # - 'fonts-ipafont'
  # - 'fonts-vlgothic'
  - 'htop'
  - 'bc'
  # - 'python-pip'
  # - 'python3'
  # - 'python3-pip'
  # - 'vifm'
  - 'tig'
  - 'debian-goodies'
  - 'jq'
  - 'facter'
  - 'zip'
  - 'unzip'
  - 'sshfs'
nakahiro386_apt_absent_packages:
  - 'nano'
  # - 'tmux'
nakahiro386_apt_cache_valid_time: 21600
