---
- hosts: all
  become: no
  gather_facts: yes
  environment: "{{ environment_vars }}"
  vars:
    vim_force_build: false
  pre_tasks:
    - block:
      - name: Test connection
        ping:
      tags: pre_tasks
  roles:
    - role: nakahiro386.apt
      become: yes
    - role: nakahiro386.dotfiles
    - role: nakahiro386.vim
      become: yes
  tasks:
    - block:
      - name: Install Docker required packages.
        apt:
          pkg: "{{ docker_required_packages }}"
          state: present
      - name: Add Docker official GPG key
        apt_key:
          id: 0EBFCD88
          url: https://download.docker.com/linux/ubuntu/gpg
          state: present
      - name: Add Docker stable apt repository
        apt_repository:
          repo: "{{ docker_apt_repository }}"
          state: present
        register: add_apt_repository
      - name: Install Docker packages
        apt:
          pkg: "{{ docker_packages }}"
          state: present
          update_cache: "{{ add_apt_repository.changed }}"
      - name: get docker-compose {{ docker_compose_version }}
        get_url:
          url: "{{ docker_compose_url }}"
          dest: /usr/local/bin/docker-compose
          owner: 'root'
          group: 'root'
          mode: 'u=rwx,g=rx,o=rx'
          checksum: "{{ docker_compose_checksum }}"
      - name: get docker-compose bash completion {{ docker_compose_version }}
        get_url:
          url: "{{ docker_compose_bash_completion_url }}"
          dest: /etc/bash_completion.d/docker-compose
          owner: 'root'
          group: 'root'
          mode: 'u=rw,g=r,o=r'
          checksum: "{{ docker_compose_bash_completion_checksum }}"
      tags: 'docker'
      become: yes
  post_tasks:

