---
- hosts: all
  become: no
  gather_facts: yes
  environment: "{{ environment_vars }}"
  vars:
    vim_force_build: false
  pre_tasks:
    - block:
      - name: Test connection
        ping:
      tags: pre_tasks
  roles:
    - role: nakahiro386.apt
      become: yes
    - role: nakahiro386.vim
      become: yes
  tasks:
    - block:
      - name: Install Docker required packages.
        apt:
          pkg: "{{ docker_required_packages }}"
          state: present
      - name: Add Docker official GPG key
        apt_key:
          id: 0EBFCD88
          url: https://download.docker.com/linux/ubuntu/gpg
          state: present
      - name: Add Docker stable apt repository
        apt_repository:
          repo: "{{ docker_apt_repository }}"
          state: present
      - name: Install Docker packages
        apt:
          pkg: "{{ docker_packages }}"
          state: present
      - name: get docker-compose {{ docker_compose_version }}
        get_url:
          url: "{{ docker_compose_url }}"
          dest: /usr/local/bin/docker-compose
          owner: 'root'
          group: 'root'
          mode: 'u=rwx,g=rx,o=rx'
          checksum: "{{ docker_compose_checksum }}"
      - name: get docker-compose bash completion {{ docker_compose_version }}
        get_url:
          url: "{{ docker_compose_bash_completion_url }}"
          dest: /etc/bash_completion.d/docker-compose
          owner: 'root'
          group: 'root'
          mode: 'u=rw,g=r,o=r'
          checksum: "{{ docker_compose_bash_completion_checksum }}"
      tags: 'docker'
      become: yes

    - block:
      - name: Install vifm required packages.
        apt:
          pkg: "{{ vifm_required_packages }}"
          state: present
      - name: Install vifm additional packages.
        apt:
          pkg: "{{ vifm_additional_packages }}"
          state: present
      - name: "git clone vifm to {{ vifm_src_dir }}"
        git:
          repo: "{{ vifm_git_url }}"
          dest: "{{ vifm_src_dir }}"
          version: "{{ vifm_version }}"
          force: yes
        register: vifm_clone
        diff: no
      - name: set vifm_build
        set_fact:
          vifm_build: "{{ vifm_clone is changed or vifm_force_build }}"

      - name: run scripts/fix-timestamps script
        command: "scripts/fix-timestamps"
        args:
          chdir: "{{ vifm_src_dir }}"
        when: vifm_clone.before is none

      - block:
        - name: configure vifm
          command: "{{ vifm_configure_command }}"
          args:
            chdir: "{{ vifm_src_dir }}"

        - name: make vifm
          make:
            chdir: "{{ vifm_src_dir }}"
            target: all

        - name: make install vifm
          make:
            chdir: "{{ vifm_src_dir }}"
            target: install
        when: vifm_build | bool
      tags: 'vifm'
      become: yes

    - block:
      - name: Add lazygit apt repository
        apt_repository:
          repo: ppa:lazygit-team/release
          state: present
      - name: Install lazygit  packages
        apt:
          pkg: lazygit
          state: present
      tags: 'lazygit'
      become: yes

  post_tasks:

